function createfigure(X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 20-Oct-2012 07:57:45

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1);

% Create title
title({'S-k'});

% Create xlabel
xlabel({'k'});

% Create ylabel
ylabel({'S'});

